_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "model_weights/pretrained_ctw1500.pth"
  ViTAEv2:
    DROP_PATH_RATE: 0.2
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.3
    VOC_SIZE: 194
    NUM_POINTS: 25
    LOSS:
      BEZIER_SAMPLE_POINTS : 25
      POINT_COORD_WEIGHT : 1.0
      POINT_LM_WEIGHT : 16.0
  BATEXT:
    CANONICAL_SIZE: 194
    VOC_SIZE: 194
    NUM_CHARS: 25

DATASETS:
  TRAIN: ("ctw1500_word_poly_train", )
  TEST: ("ctw1500_word_poly_test" ,)

INPUT:
  ROTATE: False
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (100000,)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000
  LEXICON_TYPE: 1

OUTPUT_DIR: "outputs/finetune-ctw1500/"